version: '3.1'
services:
#  php:
#    image: yii2-server
#    container_name: lamoric_server
#    depends_on:
#      - db
#    volumes:
#      - ./:/www:delegated
#      - ./Docker/apache-configure:/opt/lampp/apache2/conf.d
#    ports:
#      - '80:80'
#      - '8080:8080'
      
  db:
    image: mysql
    container_name: lamoric_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamoric_db
      MYSQL_USER: app_root
      MYSQL_PASSWORD: CHFKbdOh6FtEnCgl
    volumes:
      - ./Docker/mysql-database:/var/lib/mysql
      - ./Docker/mysql-configure:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  