<?php

use yii\db\Schema;
use yii\db\Migration;

class m180621_161422_categoryDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->batchInsert('{{%category}}',
                           ["id", "root", "lft", "rgt", "lvl", "name", "icon", "icon_type", "active", "selected", "disabled", "readonly", "visible", "collapsed", "movable_u", "movable_d", "movable_l", "movable_r", "removable", "removable_all", "created_at", "updated_at"],
                            [
    [
        'id' => '1',
        'root' => '1',
        'lft' => '1',
        'rgt' => '6',
        'lvl' => '0',
        'name' => 'Prawo',
        'icon' => 'balance-scale',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '1',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '0',
        'removable_all' => '0',
        'created_at' => '1528837252',
        'updated_at' => '1529354595',
    ],
    [
        'id' => '9',
        'root' => '9',
        'lft' => '1',
        'rgt' => '2',
        'lvl' => '0',
        'name' => 'Rodo',
        'icon' => 'user-secret',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '0',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '0',
        'removable_all' => '0',
        'created_at' => '1528890043',
        'updated_at' => '1528900941',
    ],
    [
        'id' => '10',
        'root' => '10',
        'lft' => '1',
        'rgt' => '4',
        'lvl' => '0',
        'name' => 'Dokumenty',
        'icon' => 'book',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '1',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '0',
        'removable_all' => '0',
        'created_at' => '1528890109',
        'updated_at' => '1529354587',
    ],
    [
        'id' => '11',
        'root' => '11',
        'lft' => '1',
        'rgt' => '6',
        'lvl' => '0',
        'name' => 'Artykuły',
        'icon' => 'newspaper-o',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '1',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '0',
        'removable_all' => '0',
        'created_at' => '1528890163',
        'updated_at' => '1529354602',
    ],
    [
        'id' => '12',
        'root' => '11',
        'lft' => '2',
        'rgt' => '3',
        'lvl' => '1',
        'name' => 'Przegląd prasy',
        'icon' => 'book',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '0',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '1',
        'removable_all' => '0',
        'created_at' => '1528890351',
        'updated_at' => '1528891108',
    ],
    [
        'id' => '13',
        'root' => '11',
        'lft' => '4',
        'rgt' => '5',
        'lvl' => '1',
        'name' => 'Nowości',
        'icon' => 'bell',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '0',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '1',
        'removable_all' => '0',
        'created_at' => '1528891076',
        'updated_at' => '1528891076',
    ],
    [
        'id' => '14',
        'root' => '1',
        'lft' => '2',
        'rgt' => '3',
        'lvl' => '1',
        'name' => 'Prawo Pracy',
        'icon' => 'briefcase',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '0',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '1',
        'removable_all' => '0',
        'created_at' => '1528900398',
        'updated_at' => '1528900762',
    ],
    [
        'id' => '15',
        'root' => '1',
        'lft' => '4',
        'rgt' => '5',
        'lvl' => '1',
        'name' => 'Kodeks cywilny',
        'icon' => 'male',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '0',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '1',
        'removable_all' => '0',
        'created_at' => '1528900785',
        'updated_at' => '1528900909',
    ],
    [
        'id' => '16',
        'root' => '10',
        'lft' => '2',
        'rgt' => '3',
        'lvl' => '1',
        'name' => 'Wniosek urlopowy',
        'icon' => '',
        'icon_type' => '1',
        'active' => '1',
        'selected' => '0',
        'disabled' => '0',
        'readonly' => '0',
        'visible' => '1',
        'collapsed' => '0',
        'movable_u' => '0',
        'movable_d' => '0',
        'movable_l' => '0',
        'movable_r' => '0',
        'removable' => '0',
        'removable_all' => '0',
        'created_at' => '1529353811',
        'updated_at' => '1529353811',
    ],
]
        );
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%category}} CASCADE');
    }
}
